NUM_JOINTS = 10
NUM_CONTACT_SENSORS = 4
NUM_IMU_SENSORS = 6
NUM_ROLL_PITCH = 2
ACTION_DIM = NUM_JOINTS
OBS_STACK_DIM = 3
ACTION_STACK_DIM = 0

OBSERVATION_DIM = (2 * NUM_JOINTS + NUM_CONTACT_SENSORS + NUM_IMU_SENSORS + NUM_ROLL_PITCH)
MODEL_INPUT_DIM = OBSERVATION_DIM * OBS_STACK_DIM + ACTION_DIM * ACTION_STACK_DIM


CONTROL_HZ = 50
FREQ = 100
KP = 1.0
KI = 0.0
KD = 0.0
MAX_DELTA_V = 10.0